Sequence model types refactor
WalletConnect-Labs/WalletConnectSwiftV2 pull request #210
Opened 2022-01-02 23:25 UTC by MisterVants

This refactor aims to improve the model graph of the SDK, simplify the handling + scaling of codable types, and provide a proposal of distinction for public and internal models.

It should help scaling tests and making stubbing data simpler and more straightforward on the long-term.

**Public API proposal for model types:**
- All public, session-related types, should fall under the public `Session` namespace umbrella.
- Bridging `init` methods can be provided to interchange between public and internal types when necessary.

@llbartekll these are big changes, I believe it will help scaling the code soon. Tell me if you have any insights about.

2022-01-03 09:26 UTC, llbartekll commented
> All public, session-related types, should fall under the public Session namespace umbrella.

would it make sense now to move `SessionType.Reason` to `Session` namespace and make `SessionType` internal? it could be also applied to `PairingType`

2022-01-03 12:02 UTC, MisterVants commented
Yesssss, exactly, you got the point!! That's one of the next things I'm going for

2022-01-04 11:33 UTC, llbartekll requested changes
1) I like public Session namespace but do not understand why you extracted so many internal types(Client Communication) from `SessonType` namespace.
2) Leaning the engines looks very good
3) I think we cannot have so many `CryptoKit` dependencies. Those modules should depend on abstraction. IMHO previous approach was better.
4) Only two types of WC responses are handled but I believe it is postponed for later
5) your approach for WCrelay looks good

2022-01-04 14:32 UTC, MisterVants commented on Sources/WalletConnect/Engine/SessionEngine.swift
> +        }
Yes, they can just be added as new cases

2022-01-04 14:37 UTC, MisterVants commented on Sources/WalletConnect/Engine/SessionEngine.swift
> +            crypto.deletePrivateKey(for: pendingSession.publicKey)
I think it's the only way to let the client know that the approval failed, we should add it later

2022-01-04 14:48 UTC, MisterVants commented on Sources/WalletConnect/Crypto/Crypto.swift
> +            return nil
Agreed, I'll check a solution

2022-01-04 14:51 UTC, MisterVants commented on Sources/WalletConnect/Types/ClientSynchJSONRPC/ClientSynchJSONRPC_Params.swift
>          case pairingUpgrade(PairingType.UpgradeParams)
I think I've written this before deciding what to do with the `Session` sub-types. I need to revisit it.

2022-01-05 20:49 UTC, merged