#25 integration tests
WalletConnect-Labs/WalletConnectSwiftV2 pull request #47
Opened 2021-09-16 01:48 UTC by MisterVants

Adds an integration test target with a Relay test for subscribe APIs.

The end-to-end payload test using the staging server is still flaky, sometimes it passes, sometimes it fails, still need to understand why.

2021-09-16 08:23 UTC, llbartekll requested changes
I think we need to synch with those changes.

2021-09-16 08:23 UTC, llbartekll commented on Sources/WalletConnect/Relay/Relay.swift
> +        payloadCancellable = clientSynchJsonRpcPublisher
@MisterVants  my intention was that `clientSynchJsonRpcPublisher` allows to have many subscribers on clientsynch payloads. And any subscriber is able to filtered out incomming messages by related subscription id - one relay, many subscribers. with `onPayload` approach we can have only one to one relation.

2021-09-16 13:31 UTC, llbartekll commented on Sources/WalletConnect/Relay/Relay.swift
> +        payloadCancellable = clientSynchJsonRpcPublisher
check [this](https://github.com/WalletConnect-Labs/WalletConnectSwiftV2/blob/a3089ae5d49b374734d3ca1fe26c8b1b724c6eeb/Sources/WalletConnect/Subscription/WCSubscribing.swift#L62) out

2021-09-16 13:41 UTC, MisterVants commented on Tests/IntegrationTests/RelayTests.swift
> +    func testEndToEndPayload() {
It's not related to timeout, I tried bigger timeouts and it keeps failing sometimes, I couldn't find the answer yet. It just that the second subscription payload is never received and it stops there.

2021-09-16 13:43 UTC, llbartekll commented on Tests/IntegrationTests/RelayTests.swift
> +    func testEndToEndPayload() {
hmm interesting 🤔  maybe we should debug it with proxy...?

2021-09-16 13:45 UTC, MisterVants commented on Sources/WalletConnect/Relay/Relay.swift
> +        payloadCancellable = clientSynchJsonRpcPublisher
You're right, I overlooked that for the test, the relay needs to notify multiple subscribers. I'll revert that.

2021-09-16 13:47 UTC, MisterVants commented on Sources/WalletConnect/Relay/Relay.swift
> +        } else if let response = tryDecode(JSONRPCResponse<Bool>.self, from: payload) {
You got a point, I think multiple functions doing the same thing is not good, but there is this semantic issue. Do you have any suggestion?

2021-09-16 14:14 UTC, llbartekll commented on Sources/WalletConnect/Relay/Relay.swift
> +        } else if let response = tryDecode(JSONRPCResponse<Bool>.self, from: payload) {
personally I would leave named function with a single line tryDecode body. like:
getRequestAcknowledgement() {tryDecode(JSONRPCResponse<Bool>.self, from: payload)}
but it is a small thing, won't argue :)

2021-09-16 14:15 UTC, llbartekll commented on Sources/WalletConnect/Relay/Relay.swift
> +        payloadCancellable = clientSynchJsonRpcPublisher
👍

2021-09-16 16:47 UTC, MisterVants commented on Sources/WalletConnect/Relay/Relay.swift
> +        } else if let response = tryDecode(JSONRPCResponse<Bool>.self, from: payload) {
We can also use a local `typealias` to specify the types, like `typealias RequestAcknowledgement = JSONRPCResponse<Bool>` for example, what do you think?

2021-09-17 06:26 UTC, llbartekll commented on Sources/WalletConnect/Relay/Relay.swift
> +        } else if let response = tryDecode(JSONRPCResponse<Bool>.self, from: payload) {
sounds good to me

2021-09-21 06:53 UTC, llbartekll approved these changes

2021-09-21 07:04 UTC, merged